default_language_version:
    python: python3.10

default_stages: [commit]

repos:

    -   repo: https://github.com/commitizen-tools/commitizen
        rev: v2.23.0
        hooks:
        -   id: commitizen
            stages: [commit-msg]

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace

    -   repo: https://github.com/kynan/nbstripout
        rev: 0.5.0
        hooks:
        -    id: nbstripout
             files: ".ipynb$"

    -   repo: local
        hooks:

        -   id: add-trailing-comma
            name: add-trailing-comma
            entry: add-trailing-comma
            types: [python]
            language: system

        -   id: black
            name: black
            description: python code formatter
            language: system
            files: ^gps_activity/^tests/
            types: [file, python]
            exclude: __pycache__|env|venv|data
            args: ["--line-length=120"]
            entry: black

        -   id: flake8
            name: flake8
            description: Flake8 linting check
            files: ^gps_activity/^tests/
            exclude: __pycache__|env|venv|data
            entry: flake8
            language: system
            types: [python]

        -   id: pylint
            name: pylint
            description: Pylint linting check
            files: ^gps_activity/^tests/
            entry: pylint
            language: system
            types: [python]
            args: ["--rcfile=pylint.rc", "--disable=E0402,E0611"]
